### ISSUE TITLE
Freezing and animation issues

### ISSUE THREAD

**Issue by EndlessFractal** [t3chn0m4g3/t-pot-attack-map#4]
Hello!

Thanks for your work porting the attack map!

I'm running Firefox 109 on Windows 10.

While using it I ran into a couple of issues:
- After some attacks are logged, if you try to zoom in, the map freezes preventing from dragging it again, forcing a refresh.
- When I'm able to drag, the attacked locations on the map don't stay in the appropriate locations, overlapping other countries/regions.
- Some times the animations are clipped, even though the map is fully visible, as if there's an invisible block in front.

I've attached a small video demonstrating the first two issues:

[Video.webm](https://user-images.githubusercontent.com/89462237/215905566-0d762ed4-6b20-4e69-a5ce-6c3c4bad4443.webm)

Thank you!

**Comment by EndlessFractal** [comment]
I've verified that this problem does not occur on the latest version (109.0.5414.119) of Google Chrome.

**Comment by t3chn0m4g3** [comment]
Thanks for reporting. While I can reproduce on FF, the issue is most likely related to the differences in how WebKit and Quantum (Firefox's web engine) handle certain aspects of the Mapbox and Leaflet libraries.

Since Chrome, Safari, Brave and Edge do not show any issues I suggest to use a WebKit related browser.

**Comment by t3chn0m4g3** [comment]
With the new release (3.0.0) Firefox works now as well.
